### ISSUE TITLE
go-mode from MELPA Stable

### ISSUE THREAD

**Issue by paulbdavis** [yasuyk/helm-go-package#3]
The version number for go-mode in MELPA Stable is currently 1.3.1, which does not pass your version checker [here](https://github.com/yasuyk/helm-go-package/blob/master/helm-go-package.el#L8). 

Would it be possible to set up like helm is, just requiring 1.0 instead?

**Comment by yasuyk** [comment]
@paulbdavis Sorry for the very delayed response.
i updated dependencies version. a8e00ba4cce74c115cb1b33ca590c79e7ea3bae5
